import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/public/favicon.ico";
import Header from "@/components/Header/Navbar";
import "react-toastify/dist/ReactToastify.min.css";
import 'bootstrap/dist/css/bootstrap.min.css';
// import '../node_modules/react-modal-video/scss/modal-video.scss';
import 'swiper/css';
import 'swiper/css/pagination';
import '@/styles/animate.css'
import '@/styles/fontawesome.css';
import '@/styles/themify-icons.css';
import '@/styles/animate.css';
import '@/styles/sass/style.scss';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Head from "next/head";
import Footer from "@/components/Footer/Footer";
import "@/styles/globals.css";


export const metadata: Metadata = {
  title: "Cloudzone Information Technology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <Header />
        <div  style={{marginTop:'130px'}}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
